version: 0.1

phases:
  pre_build:
    commands:
      - echo Pre Build...
      - apt-get install -y wget
      - wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip
      - unzip packer_1.3.3_linux_amd64.zip
      - chmod +x ./packer
      - ./packer -v
      #- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
        #      - echo Building the Docker image...
        #      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -t $IMAGE_REPO_NAME:`cat version` .
        #      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        #      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        #      - docker tag $IMAGE_REPO_NAME:`cat version` $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`cat version`
        #      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`cat version`

  post_build:
    commands:
      - echo Build completed on `date`
      
